"""
Extended Global Cities Crime & Safety Intelligence Dataset
Supplements backend/global_cities_data.py with 35+ additional countries
and 70+ metropolitan cities across Asia, Europe, Middle East, Latin America, and Africa.
"""

from typing import List, Dict, Any

ADDITIONAL_GLOBAL_CITIES: List[Dict[str, Any]] = [
    # -------------------------------------------------------------------------
    # NORTH AMERICA - UNITED STATES (Additional Major Metros)
    # -------------------------------------------------------------------------
    {
        "city_name": "Houston",
        "country": "United States",
        "country_code": "US",
        "flag": "🇺🇸",
        "region": "North America",
        "population_millions": 2.30,
        "lat": 29.7604,
        "lng": -95.3698,
        "crime_index": 62.4,
        "safety_index": 37.6,
        "crime_rate_per_100k": 3610,
        "violent_crime_rate_per_100k": 920,
        "risk_tier": "Elevated",
        "emergency_number": "911",
        "police_agency": "Houston Police Department (HPD)",
        "is_live_db": False,
        "districts": [
            {"id": "HOU-DT", "name": "Downtown / Midtown"},
            {"id": "HOU-NE", "name": "Northeast Patrol"},
            {"id": "HOU-SW", "name": "Southwest / Galleria"}
        ]
    },
    {
        "city_name": "Miami",
        "country": "United States",
        "country_code": "US",
        "flag": "🇺🇸",
        "region": "North America",
        "population_millions": 0.44,
        "lat": 25.7617,
        "lng": -80.1918,
        "crime_index": 52.1,
        "safety_index": 47.9,
        "crime_rate_per_100k": 3150,
        "violent_crime_rate_per_100k": 680,
        "risk_tier": "Moderate",
        "emergency_number": "911",
        "police_agency": "City of Miami Police Department (MPD)",
        "is_live_db": False,
        "districts": [
            {"id": "MIA-DT", "name": "Downtown / Brickell"},
            {"id": "MIA-LH", "name": "Little Havana / Wynwood"},
            {"id": "MIA-CP", "name": "Coconut Grove"}
        ]
    },
    {
        "city_name": "San Francisco",
        "country": "United States",
        "country_code": "US",
        "flag": "🇺🇸",
        "region": "North America",
        "population_millions": 0.81,
        "lat": 37.7749,
        "lng": -122.4194,
        "crime_index": 61.2,
        "safety_index": 38.8,
        "crime_rate_per_100k": 4920,
        "violent_crime_rate_per_100k": 540,
        "risk_tier": "Elevated",
        "emergency_number": "911",
        "police_agency": "San Francisco Police Department (SFPD)",
        "is_live_db": False,
        "districts": [
            {"id": "SF-CEN", "name": "Central (Financial / Wharf)"},
            {"id": "SF-MIS", "name": "Mission District"},
            {"id": "SF-TEN", "name": "Tenderloin & Civic Center"},
            {"id": "SF-SOU", "name": "Southern / SoMa"}
        ]
    },
    {
        "city_name": "Washington D.C.",
        "country": "United States",
        "country_code": "US",
        "flag": "🇺🇸",
        "region": "North America",
        "population_millions": 0.68,
        "lat": 38.9072,
        "lng": -77.0369,
        "crime_index": 59.8,
        "safety_index": 40.2,
        "crime_rate_per_100k": 4200,
        "violent_crime_rate_per_100k": 990,
        "risk_tier": "Elevated",
        "emergency_number": "911",
        "police_agency": "Metropolitan Police Department of DC (MPDC)",
        "is_live_db": False,
        "districts": [
            {"id": "DC-1D", "name": "First District (Downtown / Capitol)"},
            {"id": "DC-2D", "name": "Second District (Georgetown)"},
            {"id": "DC-3D", "name": "Third District (Columbia Heights)"}
        ]
    },

    # -------------------------------------------------------------------------
    # NORTH AMERICA - CANADA (Additional Major Metros)
    # -------------------------------------------------------------------------
    {
        "city_name": "Montreal",
        "country": "Canada",
        "country_code": "CA",
        "flag": "🇨🇦",
        "region": "North America",
        "population_millions": 1.76,
        "lat": 45.5017,
        "lng": -73.5673,
        "crime_index": 34.5,
        "safety_index": 65.5,
        "crime_rate_per_100k": 2100,
        "violent_crime_rate_per_100k": 280,
        "risk_tier": "Low / Safe",
        "emergency_number": "911",
        "police_agency": "Service de police de la Ville de Montréal (SPVM)",
        "is_live_db": False,
        "districts": [
            {"id": "MTL-VILLE", "name": "Poste de quartier 20 (Centre-Ville)"},
            {"id": "MTL-PLATEAU", "name": "Poste de quartier 38 (Le Plateau)"},
            {"id": "MTL-OLD", "name": "Poste de quartier 21 (Vieux-Montréal)"}
        ]
    },

    # -------------------------------------------------------------------------
    # EUROPE - ADDITIONAL COUNTRIES & METROS
    # -------------------------------------------------------------------------
    {
        "city_name": "Manchester",
        "country": "United Kingdom",
        "country_code": "GB",
        "flag": "🇬🇧",
        "region": "Europe",
        "population_millions": 0.55,
        "lat": 53.4808,
        "lng": -2.2426,
        "crime_index": 56.4,
        "safety_index": 43.6,
        "crime_rate_per_100k": 3450,
        "violent_crime_rate_per_100k": 760,
        "risk_tier": "Moderate",
        "emergency_number": "999 / 112",
        "police_agency": "Greater Manchester Police (GMP)",
        "is_live_db": False,
        "districts": [
            {"id": "MAN-CEN", "name": "City Centre Sector"},
            {"id": "MAN-NOR", "name": "North Manchester Division"},
            {"id": "MAN-SOU", "name": "South Manchester Division"}
        ]
    },
    {
        "city_name": "Edinburgh",
        "country": "United Kingdom",
        "country_code": "GB",
        "flag": "🇬🇧",
        "region": "Europe",
        "population_millions": 0.53,
        "lat": 55.9533,
        "lng": -3.1883,
        "crime_index": 31.8,
        "safety_index": 68.2,
        "crime_rate_per_100k": 2100,
        "violent_crime_rate_per_100k": 260,
        "risk_tier": "Low / Safe",
        "emergency_number": "999 / 112",
        "police_agency": "Police Scotland (Edinburgh Division)",
        "is_live_db": False,
        "districts": [
            {"id": "EDI-OLD", "name": "Old Town & Royal Mile"},
            {"id": "EDI-NEW", "name": "New Town & Stockbridge"},
            {"id": "EDI-LEITH", "name": "Leith & Portobello"}
        ]
    },
    {
        "city_name": "Vienna",
        "country": "Austria",
        "country_code": "AT",
        "flag": "🇦🇹",
        "region": "Europe",
        "population_millions": 1.98,
        "lat": 48.2082,
        "lng": 16.3738,
        "crime_index": 26.5,
        "safety_index": 73.5,
        "crime_rate_per_100k": 1820,
        "violent_crime_rate_per_100k": 150,
        "risk_tier": "Low / Safe",
        "emergency_number": "133 / 112",
        "police_agency": "Landespolizeidirektion Wien",
        "is_live_db": False,
        "districts": [
            {"id": "VIE-INN", "name": "Innere Stadt (1. Bezirk)"},
            {"id": "VIE-LEO", "name": "Leopoldstadt (2. Bezirk)"},
            {"id": "VIE-NEU", "name": "Neubau (7. Bezirk)"}
        ]
    },
    {
        "city_name": "Brussels",
        "country": "Belgium",
        "country_code": "BE",
        "flag": "🇧🇪",
        "region": "Europe",
        "population_millions": 1.22,
        "lat": 50.8503,
        "lng": 4.3517,
        "crime_index": 54.2,
        "safety_index": 45.8,
        "crime_rate_per_100k": 3200,
        "violent_crime_rate_per_100k": 580,
        "risk_tier": "Moderate",
        "emergency_number": "101 / 112",
        "police_agency": "Police Zone Bruxelles-CAPITALE-Ixelles",
        "is_live_db": False,
        "districts": [
            {"id": "BRU-CEN", "name": "Pentagone / Centre"},
            {"id": "BRU-IXL", "name": "Ixelles / Elsene"},
            {"id": "BRU-SCH", "name": "Schaerbeek"}
        ]
    },
    {
        "city_name": "Stockholm",
        "country": "Sweden",
        "country_code": "SE",
        "flag": "🇸🇪",
        "region": "Europe",
        "population_millions": 0.98,
        "lat": 59.3293,
        "lng": 18.0686,
        "crime_index": 44.8,
        "safety_index": 55.2,
        "crime_rate_per_100k": 2900,
        "violent_crime_rate_per_100k": 390,
        "risk_tier": "Low / Safe",
        "emergency_number": "112",
        "police_agency": "Polismyndigheten Region Stockholm",
        "is_live_db": False,
        "districts": [
            {"id": "STO-NOR", "name": "Norrmalm & Gamla Stan"},
            {"id": "STO-SOD", "name": "Södermalm"},
            {"id": "STO-OST", "name": "Östermalm & Djurgården"}
        ]
    },
    {
        "city_name": "Oslo",
        "country": "Norway",
        "country_code": "NO",
        "flag": "🇳🇴",
        "region": "Europe",
        "population_millions": 0.70,
        "lat": 59.9139,
        "lng": 10.7522,
        "crime_index": 33.2,
        "safety_index": 66.8,
        "crime_rate_per_100k": 2150,
        "violent_crime_rate_per_100k": 210,
        "risk_tier": "Low / Safe",
        "emergency_number": "112",
        "police_agency": "Oslo politidistrikt",
        "is_live_db": False,
        "districts": [
            {"id": "OSL-SENT", "name": "Sentrum & Grønland"},
            {"id": "OSL-FRO", "name": "Frogner & Majorstuen"},
            {"id": "OSL-GRU", "name": "Grünerløkka"}
        ]
    },
    {
        "city_name": "Copenhagen",
        "country": "Denmark",
        "country_code": "DK",
        "flag": "🇩🇰",
        "region": "Europe",
        "population_millions": 0.65,
        "lat": 55.6761,
        "lng": 12.5683,
        "crime_index": 26.8,
        "safety_index": 73.2,
        "crime_rate_per_100k": 1850,
        "violent_crime_rate_per_100k": 160,
        "risk_tier": "Low / Safe",
        "emergency_number": "112",
        "police_agency": "Københavns Politi",
        "is_live_db": False,
        "districts": [
            {"id": "CPH-IND", "name": "Indre By (City Centre)"},
            {"id": "CPH-NOR", "name": "Nørrebro & Østerbro"},
            {"id": "CPH-VES", "name": "Vesterbro & Kgs. Enghave"}
        ]
    },
    {
        "city_name": "Helsinki",
        "country": "Finland",
        "country_code": "FI",
        "flag": "🇫🇮",
        "region": "Europe",
        "population_millions": 0.66,
        "lat": 60.1699,
        "lng": 24.9384,
        "crime_index": 24.9,
        "safety_index": 75.1,
        "crime_rate_per_100k": 1780,
        "violent_crime_rate_per_100k": 140,
        "risk_tier": "Low / Safe",
        "emergency_number": "112",
        "police_agency": "Helsingin poliisilaitos",
        "is_live_db": False,
        "districts": [
            {"id": "HEL-KLU", "name": "Kluuvi & Kamppi"},
            {"id": "HEL-KAL", "name": "Kallio & Vallila"},
            {"id": "HEL-PUN", "name": "Punavuori & Ullanlinna"}
        ]
    },
    {
        "city_name": "Dublin",
        "country": "Ireland",
        "country_code": "IE",
        "flag": "🇮🇪",
        "region": "Europe",
        "population_millions": 1.26,
        "lat": 53.3498,
        "lng": -6.2603,
        "crime_index": 52.6,
        "safety_index": 47.4,
        "crime_rate_per_100k": 3100,
        "violent_crime_rate_per_100k": 480,
        "risk_tier": "Moderate",
        "emergency_number": "999 / 112",
        "police_agency": "Garda Síochána (Dublin Metropolitan Region)",
        "is_live_db": False,
        "districts": [
            {"id": "DUB-D1", "name": "Dublin 1 (O'Connell St / North Inner)"},
            {"id": "DUB-D2", "name": "Dublin 2 (Temple Bar / South Inner)"},
            {"id": "DUB-D8", "name": "Dublin 8 (Liberties / Portobello)"}
        ]
    },
    {
        "city_name": "Lisbon",
        "country": "Portugal",
        "country_code": "PT",
        "flag": "🇵🇹",
        "region": "Europe",
        "population_millions": 0.55,
        "lat": 38.7223,
        "lng": -9.1393,
        "crime_index": 29.4,
        "safety_index": 70.6,
        "crime_rate_per_100k": 1950,
        "violent_crime_rate_per_100k": 180,
        "risk_tier": "Low / Safe",
        "emergency_number": "112",
        "police_agency": "Polícia de Segurança Pública (Comando de Lisboa)",
        "is_live_db": False,
        "districts": [
            {"id": "LIS-BAI", "name": "Baixa & Chiado"},
            {"id": "LIS-ALF", "name": "Alfama & Castelo"},
            {"id": "LIS-BEL", "name": "Belém & Ajuda"}
        ]
    },
    {
        "city_name": "Athens",
        "country": "Greece",
        "country_code": "GR",
        "flag": "🇬🇷",
        "region": "Europe",
        "population_millions": 0.66,
        "lat": 37.9838,
        "lng": 23.7275,
        "crime_index": 55.8,
        "safety_index": 44.2,
        "crime_rate_per_100k": 3300,
        "violent_crime_rate_per_100k": 420,
        "risk_tier": "Moderate",
        "emergency_number": "100 / 112",
        "police_agency": "Hellenic Police (Attica General Police Directorate)",
        "is_live_db": False,
        "districts": [
            {"id": "ATH-SYN", "name": "Syntagma & Plaka"},
            {"id": "ATH-EXA", "name": "Exarcheia & Omonoia"},
            {"id": "ATH-MON", "name": "Monastiraki & Psirri"}
        ]
    },
    {
        "city_name": "Warsaw",
        "country": "Poland",
        "country_code": "PL",
        "flag": "🇵🇱",
        "region": "Europe",
        "population_millions": 1.79,
        "lat": 52.2297,
        "lng": 21.0122,
        "crime_index": 26.2,
        "safety_index": 73.8,
        "crime_rate_per_100k": 1720,
        "violent_crime_rate_per_100k": 140,
        "risk_tier": "Low / Safe",
        "emergency_number": "997 / 112",
        "police_agency": "Komenda Stołeczna Policji",
        "is_live_db": False,
        "districts": [
            {"id": "WAW-SRO", "name": "Śródmieście (City Centre)"},
            {"id": "WAW-MOK", "name": "Mokotów"},
            {"id": "WAW-PRA", "name": "Praga-Północ"}
        ]
    },
    {
        "city_name": "Prague",
        "country": "Czech Republic",
        "country_code": "CZ",
        "flag": "🇨🇿",
        "region": "Europe",
        "population_millions": 1.33,
        "lat": 50.0755,
        "lng": 14.4378,
        "crime_index": 24.1,
        "safety_index": 75.9,
        "crime_rate_per_100k": 1690,
        "violent_crime_rate_per_100k": 120,
        "risk_tier": "Low / Safe",
        "emergency_number": "158 / 112",
        "police_agency": "Policie České republiky (KŘP hl. m. Prahy)",
        "is_live_db": False,
        "districts": [
            {"id": "PRG-P1", "name": "Prague 1 (Staré Město & Malá Strana)"},
            {"id": "PRG-P2", "name": "Prague 2 (Vinohrady)"},
            {"id": "PRG-P5", "name": "Prague 5 (Smíchov)"}
        ]
    },
    {
        "city_name": "Budapest",
        "country": "Hungary",
        "country_code": "HU",
        "flag": "🇭🇺",
        "region": "Europe",
        "population_millions": 1.75,
        "lat": 47.4979,
        "lng": 19.0402,
        "crime_index": 35.1,
        "safety_index": 64.9,
        "crime_rate_per_100k": 2180,
        "violent_crime_rate_per_100k": 190,
        "risk_tier": "Low / Safe",
        "emergency_number": "107 / 112",
        "police_agency": "Budapesti Rendőr-főkapitányság (BRFK)",
        "is_live_db": False,
        "districts": [
            {"id": "BUD-D5", "name": "District V (Belváros-Lipótváros)"},
            {"id": "BUD-D7", "name": "District VII (Erzsébetváros / Jewish Quarter)"},
            {"id": "BUD-D1", "name": "District I (Várkerület / Castle)"}
        ]
    },
    {
        "city_name": "Bucharest",
        "country": "Romania",
        "country_code": "RO",
        "flag": "🇷🇴",
        "region": "Europe",
        "population_millions": 1.83,
        "lat": 44.4268,
        "lng": 26.1025,
        "crime_index": 31.2,
        "safety_index": 68.8,
        "crime_rate_per_100k": 1980,
        "violent_crime_rate_per_100k": 170,
        "risk_tier": "Low / Safe",
        "emergency_number": "112",
        "police_agency": "Poliția Capitalei (DGPMB)",
        "is_live_db": False,
        "districts": [
            {"id": "BUC-S1", "name": "Sector 1 (Centru & Nord)"},
            {"id": "BUC-S3", "name": "Sector 3 (Centru Istoric)"},
            {"id": "BUC-S6", "name": "Sector 6 (Militari & Drumul Taberei)"}
        ]
    },
    {
        "city_name": "Istanbul",
        "country": "Turkey",
        "country_code": "TR",
        "flag": "🇹🇷",
        "region": "Europe",
        "population_millions": 15.63,
        "lat": 41.0082,
        "lng": 28.9784,
        "crime_index": 48.6,
        "safety_index": 51.4,
        "crime_rate_per_100k": 2750,
        "violent_crime_rate_per_100k": 380,
        "risk_tier": "Moderate",
        "emergency_number": "112 / 155",
        "police_agency": "İstanbul İl Emniyet Müdürlüğü",
        "is_live_db": False,
        "districts": [
            {"id": "IST-FAT", "name": "Fatih (Sultanahmet)"},
            {"id": "IST-BEY", "name": "Beyoğlu (Taksim & Galata)"},
            {"id": "IST-KAD", "name": "Kadıköy (Asian Side)"},
            {"id": "IST-BES", "name": "Beşiktaş"}
        ]
    },

    # -------------------------------------------------------------------------
    # ASIA-PACIFIC - ADDITIONAL COUNTRIES & METROS
    # -------------------------------------------------------------------------
    {
        "city_name": "Beijing",
        "country": "China",
        "country_code": "CN",
        "flag": "🇨🇳",
        "region": "Asia-Pacific",
        "population_millions": 21.54,
        "lat": 39.9042,
        "lng": 116.4074,
        "crime_index": 21.4,
        "safety_index": 78.6,
        "crime_rate_per_100k": 1100,
        "violent_crime_rate_per_100k": 70,
        "risk_tier": "Low / Safe",
        "emergency_number": "110",
        "police_agency": "Beijing Municipal Public Security Bureau",
        "is_live_db": False,
        "districts": [
            {"id": "PEK-DC", "name": "Dongcheng District"},
            {"id": "PEK-XC", "name": "Xicheng District"},
            {"id": "PEK-CY", "name": "Chaoyang District"},
            {"id": "PEK-HD", "name": "Haidian District"}
        ]
    },
    {
        "city_name": "Shanghai",
        "country": "China",
        "country_code": "CN",
        "flag": "🇨🇳",
        "region": "Asia-Pacific",
        "population_millions": 24.87,
        "lat": 31.2304,
        "lng": 121.4737,
        "crime_index": 20.8,
        "safety_index": 79.2,
        "crime_rate_per_100k": 1050,
        "violent_crime_rate_per_100k": 65,
        "risk_tier": "Low / Safe",
        "emergency_number": "110",
        "police_agency": "Shanghai Municipal Public Security Bureau",
        "is_live_db": False,
        "districts": [
            {"id": "SHA-HP", "name": "Huangpu District (The Bund)"},
            {"id": "SHA-PD", "name": "Pudong New Area (Lujiazui)"},
            {"id": "SHA-JA", "name": "Jing'an District"},
            {"id": "SHA-XH", "name": "Xuhui District"}
        ]
    },
    {
        "city_name": "Taipei",
        "country": "Taiwan",
        "country_code": "TW",
        "flag": "🇹🇼",
        "region": "Asia-Pacific",
        "population_millions": 2.51,
        "lat": 25.0330,
        "lng": 121.5654,
        "crime_index": 14.8,
        "safety_index": 85.2,
        "crime_rate_per_100k": 820,
        "violent_crime_rate_per_100k": 45,
        "risk_tier": "Low / Safe",
        "emergency_number": "110",
        "police_agency": "Taipei City Police Department",
        "is_live_db": False,
        "districts": [
            {"id": "TPE-XY", "name": "Xinyi District (Taipei 101)"},
            {"id": "TPE-DA", "name": "Da'an District"},
            {"id": "TPE-ZH", "name": "Zhongzheng District"},
            {"id": "TPE-WS", "name": "Wanhua District"}
        ]
    },
    {
        "city_name": "Kuala Lumpur",
        "country": "Malaysia",
        "country_code": "MY",
        "flag": "🇲🇾",
        "region": "Asia-Pacific",
        "population_millions": 1.98,
        "lat": 3.1390,
        "lng": 101.6869,
        "crime_index": 62.8,
        "safety_index": 37.2,
        "crime_rate_per_100k": 3820,
        "violent_crime_rate_per_100k": 540,
        "risk_tier": "Elevated",
        "emergency_number": "999",
        "police_agency": "Royal Malaysia Police (IPK Kuala Lumpur)",
        "is_live_db": False,
        "districts": [
            {"id": "KUL-BB", "name": "Bukit Bintang & KLCC"},
            {"id": "KUL-BRICK", "name": "Brickfields"},
            {"id": "KUL-CHOW", "name": "Chow Kit & Dang Wangi"}
        ]
    },
    {
        "city_name": "Bangkok",
        "country": "Thailand",
        "country_code": "TH",
        "flag": "🇹🇭",
        "region": "Asia-Pacific",
        "population_millions": 10.53,
        "lat": 13.7563,
        "lng": 100.5018,
        "crime_index": 41.2,
        "safety_index": 58.8,
        "crime_rate_per_100k": 2400,
        "violent_crime_rate_per_100k": 290,
        "risk_tier": "Low / Safe",
        "emergency_number": "191 / 1155",
        "police_agency": "Metropolitan Police Bureau of Thailand",
        "is_live_db": False,
        "districts": [
            {"id": "BKK-PRAN", "name": "Phra Nakhon (Rattanakosin)"},
            {"id": "BKK-SUK", "name": "Watthana (Sukhumvit)"},
            {"id": "BKK-BANG", "name": "Bang Rak (Silom)"},
            {"id": "BKK-PATH", "name": "Pathum Wan (Siam)"}
        ]
    },
    {
        "city_name": "Ho Chi Minh City",
        "country": "Vietnam",
        "country_code": "VN",
        "flag": "🇻🇳",
        "region": "Asia-Pacific",
        "population_millions": 9.32,
        "lat": 10.8231,
        "lng": 106.6297,
        "crime_index": 53.4,
        "safety_index": 46.6,
        "crime_rate_per_100k": 2980,
        "violent_crime_rate_per_100k": 310,
        "risk_tier": "Moderate",
        "emergency_number": "113",
        "police_agency": "Ho Chi Minh City Police Department",
        "is_live_db": False,
        "districts": [
            {"id": "SGN-Q1", "name": "District 1 (Downtown / Ben Thanh)"},
            {"id": "SGN-Q3", "name": "District 3"},
            {"id": "SGN-Q7", "name": "District 7 (Phu My Hung)"}
        ]
    },
    {
        "city_name": "Jakarta",
        "country": "Indonesia",
        "country_code": "ID",
        "flag": "🇮🇩",
        "region": "Asia-Pacific",
        "population_millions": 10.56,
        "lat": -6.2088,
        "lng": 106.8456,
        "crime_index": 52.8,
        "safety_index": 47.2,
        "crime_rate_per_100k": 2900,
        "violent_crime_rate_per_100k": 340,
        "risk_tier": "Moderate",
        "emergency_number": "110 / 112",
        "police_agency": "Polda Metro Jaya (Jakarta Metropolitan Police)",
        "is_live_db": False,
        "districts": [
            {"id": "JKT-PUS", "name": "Central Jakarta (Thamrin)"},
            {"id": "JKT-SEL", "name": "South Jakarta (Senopati)"},
            {"id": "JKT-BAR", "name": "West Jakarta (Kota Tua)"}
        ]
    },
    {
        "city_name": "Manila",
        "country": "Philippines",
        "country_code": "PH",
        "flag": "🇵🇭",
        "region": "Asia-Pacific",
        "population_millions": 1.84,
        "lat": 14.5995,
        "lng": 120.9842,
        "crime_index": 64.9,
        "safety_index": 35.1,
        "crime_rate_per_100k": 4120,
        "violent_crime_rate_per_100k": 880,
        "risk_tier": "Elevated",
        "emergency_number": "911",
        "police_agency": "Manila Police District (MPD / PNP)",
        "is_live_db": False,
        "districts": [
            {"id": "MNL-ERM", "name": "Ermita & Malate"},
            {"id": "MNL-BIN", "name": "Binondo & Quiapo"},
            {"id": "MNL-TON", "name": "Tondo District"}
        ]
    },
    {
        "city_name": "Auckland",
        "country": "New Zealand",
        "country_code": "NZ",
        "flag": "🇳🇿",
        "region": "Asia-Pacific",
        "population_millions": 1.65,
        "lat": -36.8485,
        "lng": 174.7633,
        "crime_index": 48.7,
        "safety_index": 51.3,
        "crime_rate_per_100k": 2950,
        "violent_crime_rate_per_100k": 360,
        "risk_tier": "Moderate",
        "emergency_number": "111",
        "police_agency": "New Zealand Police (Auckland City District)",
        "is_live_db": False,
        "districts": [
            {"id": "AKL-CBD", "name": "Auckland CBD & Waterfront"},
            {"id": "AKL-PON", "name": "Ponsonby & Grey Lynn"},
            {"id": "AKL-NEWM", "name": "Newmarket & Parnell"}
        ]
    },

    # -------------------------------------------------------------------------
    # MIDDLE EAST - ADDITIONAL COUNTRIES & METROS
    # -------------------------------------------------------------------------
    {
        "city_name": "Doha",
        "country": "Qatar",
        "country_code": "QA",
        "flag": "🇶🇦",
        "region": "Middle East",
        "population_millions": 1.18,
        "lat": 25.2854,
        "lng": 51.5310,
        "crime_index": 16.1,
        "safety_index": 83.9,
        "crime_rate_per_100k": 880,
        "violent_crime_rate_per_100k": 38,
        "risk_tier": "Low / Safe",
        "emergency_number": "999",
        "police_agency": "Ministry of Interior - Qatar Police",
        "is_live_db": False,
        "districts": [
            {"id": "DOH-WB", "name": "West Bay & Diplomatic Area"},
            {"id": "DOH-SW", "name": "Souq Waqif & Al Jasra"},
            {"id": "DOH-PRL", "name": "The Pearl-Qatar"}
        ]
    },
    {
        "city_name": "Kuwait City",
        "country": "Kuwait",
        "country_code": "KW",
        "flag": "🇰🇼",
        "region": "Middle East",
        "population_millions": 0.60,
        "lat": 29.3759,
        "lng": 47.9774,
        "crime_index": 34.2,
        "safety_index": 65.8,
        "crime_rate_per_100k": 1920,
        "violent_crime_rate_per_100k": 160,
        "risk_tier": "Low / Safe",
        "emergency_number": "112",
        "police_agency": "Kuwait Ministry of Interior Police",
        "is_live_db": False,
        "districts": [
            {"id": "KWT-SHQ", "name": "Sharq & Dasman"},
            {"id": "KWT-SAL", "name": "Salmiya"},
            {"id": "KWT-QBL", "name": "Qibla & Mirqab"}
        ]
    },
    {
        "city_name": "Muscat",
        "country": "Oman",
        "country_code": "OM",
        "flag": "🇴🇲",
        "region": "Middle East",
        "population_millions": 1.42,
        "lat": 23.5880,
        "lng": 58.3829,
        "crime_index": 20.3,
        "safety_index": 79.7,
        "crime_rate_per_100k": 1150,
        "violent_crime_rate_per_100k": 55,
        "risk_tier": "Low / Safe",
        "emergency_number": "9999",
        "police_agency": "Royal Oman Police (ROP)",
        "is_live_db": False,
        "districts": [
            {"id": "MCT-MUT", "name": "Muttrah Corniche"},
            {"id": "MCT-QUR", "name": "Al Qurum & Shati"},
            {"id": "MCT-RUW", "name": "Ruwi Business District"}
        ]
    },
    {
        "city_name": "Tel Aviv",
        "country": "Israel",
        "country_code": "IL",
        "flag": "🇮🇱",
        "region": "Middle East",
        "population_millions": 0.47,
        "lat": 32.0853,
        "lng": 34.7818,
        "crime_index": 29.8,
        "safety_index": 70.2,
        "crime_rate_per_100k": 2100,
        "violent_crime_rate_per_100k": 190,
        "risk_tier": "Low / Safe",
        "emergency_number": "100",
        "police_agency": "Israel Police (Tel Aviv District)",
        "is_live_db": False,
        "districts": [
            {"id": "TLV-CEN", "name": "Central / Rothschild Blvd"},
            {"id": "TLV-JAF", "name": "Old Jaffa"},
            {"id": "TLV-NOR", "name": "North Tel Aviv & Port"}
        ]
    },

    # -------------------------------------------------------------------------
    # LATIN AMERICA - ADDITIONAL COUNTRIES & METROS
    # -------------------------------------------------------------------------
    {
        "city_name": "Santiago",
        "country": "Chile",
        "country_code": "CL",
        "flag": "🇨🇱",
        "region": "Latin America",
        "population_millions": 6.85,
        "lat": -33.4489,
        "lng": -70.6693,
        "crime_index": 62.3,
        "safety_index": 37.7,
        "crime_rate_per_100k": 3850,
        "violent_crime_rate_per_100k": 720,
        "risk_tier": "Elevated",
        "emergency_number": "133",
        "police_agency": "Carabineros de Chile (Prefectura Central)",
        "is_live_db": False,
        "districts": [
            {"id": "STG-CEN", "name": "Santiago Centro"},
            {"id": "STG-PRO", "name": "Providencia"},
            {"id": "STG-LAS", "name": "Las Condes"}
        ]
    },
    {
        "city_name": "Bogotá",
        "country": "Colombia",
        "country_code": "CO",
        "flag": "🇨🇴",
        "region": "Latin America",
        "population_millions": 7.90,
        "lat": 4.7110,
        "lng": -74.0721,
        "crime_index": 66.8,
        "safety_index": 33.2,
        "crime_rate_per_100k": 4350,
        "violent_crime_rate_per_100k": 850,
        "risk_tier": "Elevated",
        "emergency_number": "123",
        "police_agency": "Policía Metropolitana de Bogotá (MEBOG)",
        "is_live_db": False,
        "districts": [
            {"id": "BOG-CAN", "name": "La Candelaria"},
            {"id": "BOG-CHA", "name": "Chapinero"},
            {"id": "BOG-USA", "name": "Usaquén"}
        ]
    },
    {
        "city_name": "Lima",
        "country": "Peru",
        "country_code": "PE",
        "flag": "🇵🇪",
        "region": "Latin America",
        "population_millions": 9.75,
        "lat": -12.0464,
        "lng": -77.0428,
        "crime_index": 70.4,
        "safety_index": 29.6,
        "crime_rate_per_100k": 4600,
        "violent_crime_rate_per_100k": 940,
        "risk_tier": "High Alert",
        "emergency_number": "105",
        "police_agency": "Policía Nacional del Perú (Región Lima)",
        "is_live_db": False,
        "districts": [
            {"id": "LIM-MIR", "name": "Miraflores"},
            {"id": "LIM-BAR", "name": "Barranco"},
            {"id": "LIM-CEN", "name": "Centro Histórico"}
        ]
    },
    {
        "city_name": "Montevideo",
        "country": "Uruguay",
        "country_code": "UY",
        "flag": "🇺🇾",
        "region": "Latin America",
        "population_millions": 1.38,
        "lat": -34.9011,
        "lng": -56.1645,
        "crime_index": 52.4,
        "safety_index": 47.6,
        "crime_rate_per_100k": 3100,
        "violent_crime_rate_per_100k": 450,
        "risk_tier": "Moderate",
        "emergency_number": "911",
        "police_agency": "Jefatura de Policía de Montevideo",
        "is_live_db": False,
        "districts": [
            {"id": "MVD-CVI", "name": "Ciudad Vieja & Centro"},
            {"id": "MVD-POC", "name": "Pocitos & Punta Carretas"},
            {"id": "MVD-CRD", "name": "Cordón & Parque Rodó"}
        ]
    },
    {
        "city_name": "San José",
        "country": "Costa Rica",
        "country_code": "CR",
        "flag": "🇨🇷",
        "region": "Latin America",
        "population_millions": 0.35,
        "lat": 9.9281,
        "lng": -84.0907,
        "crime_index": 53.6,
        "safety_index": 46.4,
        "crime_rate_per_100k": 3250,
        "violent_crime_rate_per_100k": 520,
        "risk_tier": "Moderate",
        "emergency_number": "911",
        "police_agency": "Fuerza Pública de Costa Rica",
        "is_live_db": False,
        "districts": [
            {"id": "SJO-CAR", "name": "Carmen & Catedral"},
            {"id": "SJO-MER", "name": "Merced & Hospital"},
            {"id": "SJO-SAB", "name": "Sabana & Rohrmoser"}
        ]
    },

    # -------------------------------------------------------------------------
    # AFRICA - ADDITIONAL COUNTRIES & METROS
    # -------------------------------------------------------------------------
    {
        "city_name": "Lagos",
        "country": "Nigeria",
        "country_code": "NG",
        "flag": "🇳🇬",
        "region": "Africa",
        "population_millions": 15.39,
        "lat": 6.5244,
        "lng": 3.3792,
        "crime_index": 67.5,
        "safety_index": 32.5,
        "crime_rate_per_100k": 4400,
        "violent_crime_rate_per_100k": 960,
        "risk_tier": "Elevated",
        "emergency_number": "112 / 767",
        "police_agency": "Nigeria Police Force (Lagos State Command)",
        "is_live_db": False,
        "districts": [
            {"id": "LOS-ISL", "name": "Lagos Island & Marina"},
            {"id": "LOS-VI", "name": "Victoria Island & Lekki"},
            {"id": "LOS-IKJ", "name": "Ikeja (Capital District)"}
        ]
    },
    {
        "city_name": "Accra",
        "country": "Ghana",
        "country_code": "GH",
        "flag": "🇬🇭",
        "region": "Africa",
        "population_millions": 2.56,
        "lat": 5.6037,
        "lng": -0.1870,
        "crime_index": 46.8,
        "safety_index": 53.2,
        "crime_rate_per_100k": 2650,
        "violent_crime_rate_per_100k": 320,
        "risk_tier": "Moderate",
        "emergency_number": "191 / 112",
        "police_agency": "Ghana Police Service (Accra Regional Command)",
        "is_live_db": False,
        "districts": [
            {"id": "ACC-OSU", "name": "Osu & Oxford Street"},
            {"id": "ACC-AIR", "name": "Airport Residential & Roman Ridge"},
            {"id": "ACC-JAM", "name": "Jamestown & High Street"}
        ]
    },
    {
        "city_name": "Casablanca",
        "country": "Morocco",
        "country_code": "MA",
        "flag": "🇲🇦",
        "region": "Africa",
        "population_millions": 3.75,
        "lat": 33.5731,
        "lng": -7.5898,
        "crime_index": 53.8,
        "safety_index": 46.2,
        "crime_rate_per_100k": 3150,
        "violent_crime_rate_per_100k": 430,
        "risk_tier": "Moderate",
        "emergency_number": "19 / 112",
        "police_agency": "Sûreté Nationale (DGSN Casablanca)",
        "is_live_db": False,
        "districts": [
            {"id": "CAS-ANF", "name": "Anfa & Corniche"},
            {"id": "CAS-MAA", "name": "Maârif & Gauthier"},
            {"id": "CAS-MED", "name": "Ancienne Médina"}
        ]
    },
    {
        "city_name": "Kigali",
        "country": "Rwanda",
        "country_code": "RW",
        "flag": "🇷🇼",
        "region": "Africa",
        "population_millions": 1.21,
        "lat": -1.9441,
        "lng": 30.0619,
        "crime_index": 22.8,
        "safety_index": 77.2,
        "crime_rate_per_100k": 1350,
        "violent_crime_rate_per_100k": 95,
        "risk_tier": "Low / Safe",
        "emergency_number": "112",
        "police_agency": "Rwanda National Police (RNP Kigali)",
        "is_live_db": False,
        "districts": [
            {"id": "KGL-NYA", "name": "Nyarugenge (City Center)"},
            {"id": "KGL-GAS", "name": "Gasabo (Kacyiru / Embassies)"},
            {"id": "KGL-KIC", "name": "Kicukiro"}
        ]
    },
    {
        "city_name": "Bengaluru",
        "country": "India",
        "country_code": "IN",
        "flag": "🇮🇳",
        "region": "Asia-Pacific",
        "population_millions": 12.33,
        "lat": 12.9716,
        "lng": 77.5946,
        "crime_index": 48.2,
        "safety_index": 51.8,
        "crime_rate_per_100k": 2600,
        "violent_crime_rate_per_100k": 310,
        "risk_tier": "Moderate",
        "emergency_number": "112 / 100",
        "police_agency": "Bengaluru City Police (BCP)",
        "is_live_db": False,
        "districts": [
            {"id": "BLR-CEN", "name": "Central Division (Cubbon Park / MG Rd)"},
            {"id": "BLR-EAST", "name": "East Division (Indiranagar / Whitefield)"},
            {"id": "BLR-SOUTH", "name": "South Division (Koramangala / Jayanagar)"}
        ]
    },
    {
        "city_name": "Kolkata",
        "country": "India",
        "country_code": "IN",
        "flag": "🇮🇳",
        "region": "Asia-Pacific",
        "population_millions": 14.85,
        "lat": 22.5726,
        "lng": 88.3639,
        "crime_index": 42.6,
        "safety_index": 57.4,
        "crime_rate_per_100k": 1850,
        "violent_crime_rate_per_100k": 240,
        "risk_tier": "Low / Safe",
        "emergency_number": "112 / 100",
        "police_agency": "Kolkata Police Department",
        "is_live_db": False,
        "districts": [
            {"id": "CCU-CEN", "name": "Central Division (Esplanade / Park St)"},
            {"id": "CCU-SOU", "name": "South Division (Ballygunge / Alipore)"},
            {"id": "CCU-NOR", "name": "North Division (Shyambazar)"}
        ]
    },
    {
        "city_name": "Chennai",
        "country": "India",
        "country_code": "IN",
        "flag": "🇮🇳",
        "region": "Asia-Pacific",
        "population_millions": 10.97,
        "lat": 13.0827,
        "lng": 80.2707,
        "crime_index": 38.5,
        "safety_index": 61.5,
        "crime_rate_per_100k": 1920,
        "violent_crime_rate_per_100k": 220,
        "risk_tier": "Low / Safe",
        "emergency_number": "112 / 100",
        "police_agency": "Greater Chennai Police",
        "is_live_db": False,
        "districts": [
            {"id": "MAA-NOR", "name": "North Zone (George Town)"},
            {"id": "MAA-SOU", "name": "South Zone (Mylapore / Adyar)"},
            {"id": "MAA-CEN", "name": "Central Zone (T. Nagar / Anna Nagar)"}
        ]
    },
    {
        "city_name": "Hyderabad",
        "country": "India",
        "country_code": "IN",
        "flag": "🇮🇳",
        "region": "Asia-Pacific",
        "population_millions": 10.27,
        "lat": 17.3850,
        "lng": 78.4867,
        "crime_index": 43.1,
        "safety_index": 56.9,
        "crime_rate_per_100k": 2100,
        "violent_crime_rate_per_100k": 250,
        "risk_tier": "Low / Safe",
        "emergency_number": "112 / 100",
        "police_agency": "Hyderabad City Police",
        "is_live_db": False,
        "districts": [
            {"id": "HYD-CEN", "name": "Central Zone (Abids / Banjara Hills)"},
            {"id": "HYD-CYB", "name": "Cyberabad (Hitec City / Madhapur)"},
            {"id": "HYD-SOU", "name": "South Zone (Charminar / Old City)"}
        ]
    },
    {
        "city_name": "Frankfurt",
        "country": "Germany",
        "country_code": "DE",
        "flag": "🇩🇪",
        "region": "Europe",
        "population_millions": 0.76,
        "lat": 50.1109,
        "lng": 8.6821,
        "crime_index": 46.2,
        "safety_index": 53.8,
        "crime_rate_per_100k": 2980,
        "violent_crime_rate_per_100k": 360,
        "risk_tier": "Moderate",
        "emergency_number": "110 / 112",
        "police_agency": "Polizeipräsidium Frankfurt am Main",
        "is_live_db": False,
        "districts": [
            {"id": "FRA-INN", "name": "Innenstadt (Financial District)"},
            {"id": "FRA-HBF", "name": "Bahnhofsviertel"},
            {"id": "FRA-SAC", "name": "Sachsenhausen"}
        ]
    },
    {
        "city_name": "Hamburg",
        "country": "Germany",
        "country_code": "DE",
        "flag": "🇩🇪",
        "region": "Europe",
        "population_millions": 1.85,
        "lat": 53.5511,
        "lng": 9.9937,
        "crime_index": 41.5,
        "safety_index": 58.5,
        "crime_rate_per_100k": 2840,
        "violent_crime_rate_per_100k": 310,
        "risk_tier": "Low / Safe",
        "emergency_number": "110 / 112",
        "police_agency": "Polizei Hamburg",
        "is_live_db": False,
        "districts": [
            {"id": "HAM-MIT", "name": "Hamburg-Mitte & St. Pauli"},
            {"id": "HAM-ALT", "name": "Altona & Ottensen"},
            {"id": "HAM-EIM", "name": "Eimsbüttel"}
        ]
    },
    {
        "city_name": "Marseille",
        "country": "France",
        "country_code": "FR",
        "flag": "🇫🇷",
        "region": "Europe",
        "population_millions": 0.87,
        "lat": 43.2965,
        "lng": 5.3698,
        "crime_index": 65.4,
        "safety_index": 34.6,
        "crime_rate_per_100k": 4300,
        "violent_crime_rate_per_100k": 820,
        "risk_tier": "Elevated",
        "emergency_number": "17 / 112",
        "police_agency": "Direction Départementale de la Sécurité Publique (DDSP 13)",
        "is_live_db": False,
        "districts": [
            {"id": "MRS-VP", "name": "Vieux-Port & Panier (1er/2e)"},
            {"id": "MRS-NOR", "name": "Quartiers Nord (13e/14e/15e)"},
            {"id": "MRS-PRA", "name": "Prado & Corniche (8e)"}
        ]
    },
    {
        "city_name": "Lyon",
        "country": "France",
        "country_code": "FR",
        "flag": "🇫🇷",
        "region": "Europe",
        "population_millions": 0.52,
        "lat": 45.7640,
        "lng": 4.8357,
        "crime_index": 51.3,
        "safety_index": 48.7,
        "crime_rate_per_100k": 3100,
        "violent_crime_rate_per_100k": 420,
        "risk_tier": "Moderate",
        "emergency_number": "17 / 112",
        "police_agency": "Police Nationale (Direction du Rhône)",
        "is_live_db": False,
        "districts": [
            {"id": "LYS-PRE", "name": "Presqu'île (1er & 2e)"},
            {"id": "LYS-VIE", "name": "Vieux-Lyon & Fourvière (5e)"},
            {"id": "LYS-PAR", "name": "Part-Dieu (3e)"}
        ]
    },
    {
        "city_name": "Milan",
        "country": "Italy",
        "country_code": "IT",
        "flag": "🇮🇹",
        "region": "Europe",
        "population_millions": 1.40,
        "lat": 45.4642,
        "lng": 9.1900,
        "crime_index": 50.8,
        "safety_index": 49.2,
        "crime_rate_per_100k": 3400,
        "violent_crime_rate_per_100k": 380,
        "risk_tier": "Moderate",
        "emergency_number": "112 / 113",
        "police_agency": "Polizia di Stato (Questura di Milano)",
        "is_live_db": False,
        "districts": [
            {"id": "MIL-DUO", "name": "Centro Storico / Duomo"},
            {"id": "MIL-NAV", "name": "Navigli & Porta Ticinese"},
            {"id": "MIL-CEN", "name": "Stazione Centrale & Loreto"}
        ]
    },
    {
        "city_name": "Valencia",
        "country": "Spain",
        "country_code": "ES",
        "flag": "🇪🇸",
        "region": "Europe",
        "population_millions": 0.80,
        "lat": 39.4699,
        "lng": -0.3763,
        "crime_index": 26.4,
        "safety_index": 73.6,
        "crime_rate_per_100k": 1820,
        "violent_crime_rate_per_100k": 140,
        "risk_tier": "Low / Safe",
        "emergency_number": "112 / 091",
        "police_agency": "Policía Local de Valencia",
        "is_live_db": False,
        "districts": [
            {"id": "VLC-CIU", "name": "Ciutat Vella (El Carmen)"},
            {"id": "VLC-EIX", "name": "L'Eixample & Ruzafa"},
            {"id": "VLC-POB", "name": "Poblats Marítims (El Cabanyal)"}
        ]
    },
    {
        "city_name": "Kyoto",
        "country": "Japan",
        "country_code": "JP",
        "flag": "🇯🇵",
        "region": "Asia-Pacific",
        "population_millions": 1.46,
        "lat": 35.0116,
        "lng": 135.7681,
        "crime_index": 14.2,
        "safety_index": 85.8,
        "crime_rate_per_100k": 680,
        "violent_crime_rate_per_100k": 25,
        "risk_tier": "Low / Safe",
        "emergency_number": "110",
        "police_agency": "Kyoto Prefectural Police",
        "is_live_db": False,
        "districts": [
            {"id": "KYO-SHI", "name": "Shimogyo-ku (Kyoto Station)"},
            {"id": "KYO-NAK", "name": "Nakagyo-ku (Kawaramachi)"},
            {"id": "KYO-HIG", "name": "Higashiyama-ku (Gion)"}
        ]
    },
    {
        "city_name": "Busan",
        "country": "South Korea",
        "country_code": "KR",
        "flag": "🇰🇷",
        "region": "Asia-Pacific",
        "population_millions": 3.35,
        "lat": 35.1796,
        "lng": 129.0756,
        "crime_index": 24.2,
        "safety_index": 75.8,
        "crime_rate_per_100k": 1280,
        "violent_crime_rate_per_100k": 85,
        "risk_tier": "Low / Safe",
        "emergency_number": "112",
        "police_agency": "Busan Metropolitan Police Agency",
        "is_live_db": False,
        "districts": [
            {"id": "PUS-HAE", "name": "Haeundae District"},
            {"id": "PUS-BUS", "name": "Busanjin District (Seomyeon)"},
            {"id": "PUS-JUN", "name": "Jung District (Nampo-dong)"}
        ]
    },
    {
        "city_name": "Brisbane",
        "country": "Australia",
        "country_code": "AU",
        "flag": "🇦🇺",
        "region": "Asia-Pacific",
        "population_millions": 2.56,
        "lat": -27.4698,
        "lng": 153.0251,
        "crime_index": 38.6,
        "safety_index": 61.4,
        "crime_rate_per_100k": 2480,
        "violent_crime_rate_per_100k": 280,
        "risk_tier": "Low / Safe",
        "emergency_number": "000",
        "police_agency": "Queensland Police Service (Brisbane Region)",
        "is_live_db": False,
        "districts": [
            {"id": "BNE-CBD", "name": "City & Fortitude Valley"},
            {"id": "BNE-SB", "name": "South Bank & West End"},
            {"id": "BNE-NOR", "name": "North Brisbane District"}
        ]
    },
    {
        "city_name": "Geneva",
        "country": "Switzerland",
        "country_code": "CH",
        "flag": "🇨🇭",
        "region": "Europe",
        "population_millions": 0.50,
        "lat": 46.2044,
        "lng": 6.1432,
        "crime_index": 32.1,
        "safety_index": 67.9,
        "crime_rate_per_100k": 2100,
        "violent_crime_rate_per_100k": 180,
        "risk_tier": "Low / Safe",
        "emergency_number": "117 / 112",
        "police_agency": "Police cantonale de Genève",
        "is_live_db": False,
        "districts": [
            {"id": "GVA-CIT", "name": "Cité-Centre & Vieille-Ville"},
            {"id": "GVA-PAQ", "name": "Les Pâquis & Cornavin"},
            {"id": "GVA-EAU", "name": "Eaux-Vives"}
        ]
    },
    {
        "city_name": "Guangzhou",
        "country": "China",
        "country_code": "CN",
        "flag": "🇨🇳",
        "region": "Asia-Pacific",
        "population_millions": 18.68,
        "lat": 23.1291,
        "lng": 113.2644,
        "crime_index": 22.5,
        "safety_index": 77.5,
        "crime_rate_per_100k": 1180,
        "violent_crime_rate_per_100k": 72,
        "risk_tier": "Low / Safe",
        "emergency_number": "110",
        "police_agency": "Guangzhou Municipal Public Security Bureau",
        "is_live_db": False,
        "districts": [
            {"id": "CAN-TH", "name": "Tianhe District (CBD)"},
            {"id": "CAN-YX", "name": "Yuexiu District"},
            {"id": "CAN-LW", "name": "Liwan District"}
        ]
    },
    {
        "city_name": "Rio de Janeiro",
        "country": "Brazil",
        "country_code": "BR",
        "flag": "🇧🇷",
        "region": "Latin America",
        "population_millions": 6.74,
        "lat": -22.9068,
        "lng": -43.1729,
        "crime_index": 77.6,
        "safety_index": 22.4,
        "crime_rate_per_100k": 5400,
        "violent_crime_rate_per_100k": 1380,
        "risk_tier": "High Alert",
        "emergency_number": "190",
        "police_agency": "Polícia Militar do Estado do Rio de Janeiro (PMERJ)",
        "is_live_db": False,
        "districts": [
            {"id": "GIG-ZONASUL", "name": "Zona Sul (Copacabana / Ipanema)"},
            {"id": "GIG-CENTRO", "name": "Centro & Lapa"},
            {"id": "GIG-BARRA", "name": "Barra da Tijuca"}
        ]
    },
    {
        "city_name": "Cape Town",
        "country": "South Africa",
        "country_code": "ZA",
        "flag": "🇿🇦",
        "region": "Africa",
        "population_millions": 4.62,
        "lat": -33.9249,
        "lng": 18.4241,
        "crime_index": 73.8,
        "safety_index": 26.2,
        "crime_rate_per_100k": 5200,
        "violent_crime_rate_per_100k": 1420,
        "risk_tier": "High Alert",
        "emergency_number": "10111",
        "police_agency": "South African Police Service (Western Cape SAPS)",
        "is_live_db": False,
        "districts": [
            {"id": "CPT-CBD", "name": "Cape Town Central City"},
            {"id": "CPT-ATL", "name": "Atlantic Seaboard (Camps Bay)"},
            {"id": "CPT-WIN", "name": "Southern Suburbs & Wynberg"}
        ]
    },
    {
        "city_name": "Alexandria",
        "country": "Egypt",
        "country_code": "EG",
        "flag": "🇪🇬",
        "region": "Africa",
        "population_millions": 5.26,
        "lat": 31.2001,
        "lng": 29.9187,
        "crime_index": 48.9,
        "safety_index": 51.1,
        "crime_rate_per_100k": 2650,
        "violent_crime_rate_per_100k": 320,
        "risk_tier": "Moderate",
        "emergency_number": "122",
        "police_agency": "Alexandria Police Directorate",
        "is_live_db": False,
        "districts": [
            {"id": "ALY-RAM", "name": "Al Raml & Corniche"},
            {"id": "ALY-MAN", "name": "Al Mansheya"},
            {"id": "ALY-MON", "name": "Al Montazah"}
        ]
    },
    {
        "city_name": "Porto",
        "country": "Portugal",
        "country_code": "PT",
        "flag": "🇵🇹",
        "region": "Europe",
        "population_millions": 0.24,
        "lat": 41.1579,
        "lng": -8.6291,
        "crime_index": 28.2,
        "safety_index": 71.8,
        "crime_rate_per_100k": 1820,
        "violent_crime_rate_per_100k": 150,
        "risk_tier": "Low / Safe",
        "emergency_number": "112",
        "police_agency": "Polícia de Segurança Pública (Comando do Porto)",
        "is_live_db": False,
        "districts": [
            {"id": "OPO-RIB", "name": "Ribeira & Miragaia"},
            {"id": "OPO-BOA", "name": "Boavista & Cedofeita"},
            {"id": "OPO-FOZ", "name": "Foz do Douro"}
        ]
    },
    {
        "city_name": "Wellington",
        "country": "New Zealand",
        "country_code": "NZ",
        "flag": "🇳🇿",
        "region": "Asia-Pacific",
        "population_millions": 0.43,
        "lat": -41.2865,
        "lng": 174.7762,
        "crime_index": 31.4,
        "safety_index": 68.6,
        "crime_rate_per_100k": 2100,
        "violent_crime_rate_per_100k": 210,
        "risk_tier": "Low / Safe",
        "emergency_number": "111",
        "police_agency": "New Zealand Police (Wellington District)",
        "is_live_db": False,
        "districts": [
            {"id": "WLG-CBD", "name": "Wellington Central & Lambton"},
            {"id": "WLG-TEAR", "name": "Te Aro & Courtenay Place"},
            {"id": "WLG-THOR", "name": "Thorndon & Pipitea"}
        ]
    }
]

